# docker run --rm -v $PWD:/usr/local/tomcat/webapps -p 8081:8080 tomcat:latest
#
version: '3'

services:

  reverse-proxy:
    image: traefik 
    command: --docker 
    ports:
      - "8081:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  tomcat:
    image: tomcat:latest
    volumes:
      - .:/usr/local/tomcat/webapps
    ports:
      - 8080
    labels:
      - "traefik.frontend.rule=Host:sample.localhost"

# curl -H Host:sample.localhost http://localhost:8081/sample/
#

